spring:
  # Basic Config
  profiles:
    default: local
  config:
    import:
      - application-secret.yml

  webflux:
    multipart:
      max-in-memory-size: 512KB
      max-disk-usage-per-part: 10MB
      max-parts: 25

# prometheus & actuator
management:
  endpoints:
    shutdown:
      enabled: false
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: retrip-api
    distribution:
      percentiles-histogram:
        http.server.requests: true
  prometheus:
    metrics:
      export:
        enabled: true

# ReTrip Application Config
retrip:
  image:
    min-count: 5
    max-count: 20

# AWS S3 Config
aws:
  s3:
    region: ap-northeast-2
    bucket: ${aws.s3.bucket}
    access-key: ${aws.s3.access-key}
    secret-key: ${aws.s3.secret-key}

server:
  netty:
    max-initial-line-length: 8192
    max-header-size: 32768
    validate-headers: false

---
spring:
  # Profile Config
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: ${db.local.driver-class-name}
    url: ${db.local.url}
    username: ${db.local.username}
    password: ${db.local.password}

  # JPA Config
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  # Redis Config
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  codec:
    max-in-memory-size: 10MB

retrip:
  image:
    min-count: 3
    max-count: 8
    max-size-mb: 10

  processing:
    timeout-seconds: 90