global:
  scrape_interval: 15s  # 메트릭 수집 주기
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]  # Docker 환경에서 호스트 접근